config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :anexos
  resources :proveedores
  resources :equipos
  resources :consumos
  resources :facturas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login' # Por default ejecuta el controlador seguridad y el metodo login
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  get '/consumo_lista/:id', to: "consumos#index"
  get '/anexos_lista', to: "anexos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proveedore.rb
# == Schema Information
#
# Table name: proveedores
#
#  id              :integer          not null, primary key
#  idProveedor     :integer
#  identificacion  :string
#  nombre          :string
#  idCiudad        :integer
#  idDpto          :integer
#  direccion       :string
#  correo          :string
#  telefonos       :string
#  idTipoProv      :integer
#  idEstadoProv    :integer
#  idCategoriaProv :integer
#  comentario      :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Proveedore < ApplicationRecord
end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController
  before_action :set_proveedore, only: [:show, :edit, :update, :destroy]

  # GET /proveedores
  # GET /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully created.' }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: 'Proveedore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedore_params
      params.require(:proveedore).permit(:idProveedor, :identificacion, :nombre, :idCiudad, :idDpto, :direccion, :correo, :telefonos, :idTipoProv, :idEstadoProv, :idCategoriaProv, :comentario)
    end
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore, local: true) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
      <% proveedore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idProveedor %>
    <%= form.number_field :idProveedor, id: :proveedore_idProveedor %>
  </div>

  <div class="field">
    <%= form.label :identificacion %>
    <%= form.text_field :identificacion, id: :proveedore_identificacion %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :proveedore_nombre %>
  </div>

  <div class="field">
    <%= form.label :idCiudad %>
    <%= form.number_field :idCiudad, id: :proveedore_idCiudad %>
  </div>

  <div class="field">
    <%= form.label :idDpto %>
    <%= form.number_field :idDpto, id: :proveedore_idDpto %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :proveedore_direccion %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :proveedore_correo %>
  </div>

  <div class="field">
    <%= form.label :telefonos %>
    <%= form.text_field :telefonos, id: :proveedore_telefonos %>
  </div>

  <div class="field">
    <%= form.label :idTipoProv %>
    <%= form.number_field :idTipoProv, id: :proveedore_idTipoProv %>
  </div>

  <div class="field">
    <%= form.label :idEstadoProv %>
    <%= form.number_field :idEstadoProv, id: :proveedore_idEstadoProv %>
  </div>

  <div class="field">
    <%= form.label :idCategoriaProv %>
    <%= form.number_field :idCategoriaProv, id: :proveedore_idCategoriaProv %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_field :comentario, id: :proveedore_comentario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editing Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Show', @proveedore %> |
<%= link_to 'Back', proveedores_path %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>

<table>
  <thead>
    <tr>
      <th>Idproveedor</th>
      <th>Identificacion</th>
      <th>Nombre</th>
      <th>Idciudad</th>
      <th>Iddpto</th>
      <th>Direccion</th>
      <th>Correo</th>
      <th>Telefonos</th>
      <th>Idtipoprov</th>
      <th>Idestadoprov</th>
      <th>Idcategoriaprov</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><%= proveedore.idProveedor %></td>
        <td><%= proveedore.identificacion %></td>
        <td><%= proveedore.nombre %></td>
        <td><%= proveedore.idCiudad %></td>
        <td><%= proveedore.idDpto %></td>
        <td><%= proveedore.direccion %></td>
        <td><%= proveedore.correo %></td>
        <td><%= proveedore.telefonos %></td>
        <td><%= proveedore.idTipoProv %></td>
        <td><%= proveedore.idEstadoProv %></td>
        <td><%= proveedore.idCategoriaProv %></td>
        <td><%= proveedore.comentario %></td>
        <td><%= link_to 'Show', proveedore %></td>
        <td><%= link_to 'Edit', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Destroy', proveedore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proveedore', new_proveedore_path %>

app/views/proveedores/new.html.erb
<h1>New Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Back', proveedores_path %>

app/views/proveedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idproveedor:</strong>
  <%= @proveedore.idProveedor %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @proveedore.identificacion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @proveedore.nombre %>
</p>

<p>
  <strong>Idciudad:</strong>
  <%= @proveedore.idCiudad %>
</p>

<p>
  <strong>Iddpto:</strong>
  <%= @proveedore.idDpto %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @proveedore.direccion %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @proveedore.correo %>
</p>

<p>
  <strong>Telefonos:</strong>
  <%= @proveedore.telefonos %>
</p>

<p>
  <strong>Idtipoprov:</strong>
  <%= @proveedore.idTipoProv %>
</p>

<p>
  <strong>Idestadoprov:</strong>
  <%= @proveedore.idEstadoProv %>
</p>

<p>
  <strong>Idcategoriaprov:</strong>
  <%= @proveedore.idCategoriaProv %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @proveedore.comentario %>
</p>

<%= link_to 'Edit', edit_proveedore_path(@proveedore) %> |
<%= link_to 'Back', proveedores_path %>