config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :anexos
  resources :proveedores
  resources :equipos
  resources :consumos
  resources :facturas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login' # Por default ejecuta el controlador seguridad y el metodo login
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  get '/consumo_lista/:id', to: "consumos#index"
  get '/anexos_lista', to: "anexos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/opcione.rb
# == Schema Information
#
# Table name: opciones
#
#  id           :integer          not null, primary key
#  idpadre      :integer
#  opcion       :string
#  url          :string
#  estadoopcion :string
#  orden        :string
#  eshoja       :boolean
#  controller   :string
#  eliminado    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Opcione < ApplicationRecord
	has_many :rol_opcion_operacione
end

app/controllers/opciones_controller.rb
class OpcionesController < ApplicationController
  before_action :set_opcione, only: [:show, :edit, :update, :destroy]

  # GET /opciones
  # GET /opciones.json
  def index
    @opciones = Opcione.all
  end

  # GET /opciones/1
  # GET /opciones/1.json
  def show
  end

  # GET /opciones/new
  def new
    @opcione = Opcione.new
  end

  # GET /opciones/1/edit
  def edit
  end

  # POST /opciones
  # POST /opciones.json
  def create
    @opcione = Opcione.new(opcione_params)

    respond_to do |format|
      if @opcione.save
        format.html { redirect_to @opcione, notice: 'Opcione was successfully created.' }
        format.json { render :show, status: :created, location: @opcione }
      else
        format.html { render :new }
        format.json { render json: @opcione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opciones/1
  # PATCH/PUT /opciones/1.json
  def update
    respond_to do |format|
      if @opcione.update(opcione_params)
        format.html { redirect_to @opcione, notice: 'Opcione was successfully updated.' }
        format.json { render :show, status: :ok, location: @opcione }
      else
        format.html { render :edit }
        format.json { render json: @opcione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opciones/1
  # DELETE /opciones/1.json
  def destroy
    @opcione.destroy
    respond_to do |format|
      format.html { redirect_to opciones_url, notice: 'Opcione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opcione
      @opcione = Opcione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opcione_params
      params.require(:opcione).permit(:idpadre, :opcion, :url, :estadoopcion, :orden, :eshoja, :controller, :eliminado)
    end
end

app/helpers/opciones_helper.rb
module OpcionesHelper
end

app/views/opciones/_form.html.erb
<%= form_with(model: opcione, local: true) do |form| %>
  <% if opcione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opcione.errors.count, "error") %> prohibited this opcione from being saved:</h2>

      <ul>
      <% opcione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idpadre %>
    <%= form.number_field :idpadre, id: :opcione_idpadre %>
  </div>

  <div class="field">
    <%= form.label :opcion %>
    <%= form.text_field :opcion, id: :opcione_opcion %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :opcione_url %>
  </div>

  <div class="field">
    <%= form.label :estadoopcion %>
    <%= form.text_field :estadoopcion, id: :opcione_estadoopcion %>
  </div>

  <div class="field">
    <%= form.label :orden %>
    <%= form.text_field :orden, id: :opcione_orden %>
  </div>

  <div class="field">
    <%= form.label :eshoja %>
    <%= form.check_box :eshoja, id: :opcione_eshoja %>
  </div>

  <div class="field">
    <%= form.label :controller %>
    <%= form.text_field :controller, id: :opcione_controller %>
  </div>

  <div class="field">
    <%= form.label :eliminado %>
    <%= form.number_field :eliminado, id: :opcione_eliminado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/opciones/edit.html.erb
<h1>Editing Opcione</h1>

<%= render 'form', opcione: @opcione %>

<%= link_to 'Show', @opcione %> |
<%= link_to 'Back', opciones_path %>

app/views/opciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opciones</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Id_Padre</th>
      <th>Opcion</th>
      <th>Url</th>
      <th>Estado</th>
      <th>Orden</th>
      <th>Eshoja</th>
      <th>Controller</th>
      <th>Eliminado</th>
     
    </tr>
  </thead>

  <tbody>
    <% @opciones.each do |opcione| %>
      <tr>
        <td><%= opcione.id %></td>
        <td><%= opcione.idpadre %></td>
        <td><%= opcione.opcion %></td>
        <td><%= opcione.url %></td>
        <td><%= opcione.estadoopcion %></td>
        <td><%= opcione.orden %></td>
        <td><%= opcione.eshoja %></td>
        <td><%= opcione.controller %></td>
        <td><%= opcione.eliminado %></td>
        <td><%= link_to 'Show', opcione %></td>
        <td><%= link_to 'Edit', edit_opcione_path(opcione) %></td>
        <td><%= link_to 'Destroy', opcione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opcione', new_opcione_path %>

app/views/opciones/new.html.erb
<h1>New Opcione</h1>

<%= render 'form', opcione: @opcione %>

<%= link_to 'Back', opciones_path %>

app/views/opciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idpadre:</strong>
  <%= @opcione.idpadre %>
</p>

<p>
  <strong>Opcion:</strong>
  <%= @opcione.opcion %>
</p>

<p>
  <strong>Url:</strong>
  <%= @opcione.url %>
</p>

<p>
  <strong>Estadoopcion:</strong>
  <%= @opcione.estadoopcion %>
</p>

<p>
  <strong>Orden:</strong>
  <%= @opcione.orden %>
</p>

<p>
  <strong>Eshoja:</strong>
  <%= @opcione.eshoja %>
</p>

<p>
  <strong>Controller:</strong>
  <%= @opcione.controller %>
</p>

<p>
  <strong>Eliminado:</strong>
  <%= @opcione.eliminado %>
</p>

<%= link_to 'Edit', edit_opcione_path(@opcione) %> |
<%= link_to 'Back', opciones_path %>