config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :anexos
  resources :proveedores
  resources :equipos
  resources :consumos
  resources :facturas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login' # Por default ejecuta el controlador seguridad y el metodo login
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  get '/consumo_lista/:id', to: "consumos#index"
  get '/anexos_lista', to: "anexos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/valor_parametro.rb
# == Schema Information
#
# Table name: valor_parametros
#
#  id                   :integer          not null, primary key
#  parametroId          :integer
#  valor                :string
#  orden                :string(3)
#  estadoValorParametro :string(1)
#  eliminado            :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  parametro_id         :integer
#

class ValorParametro < ApplicationRecord
	 belongs_to :parametro
end

app/controllers/valor_parametros_controller.rb
class ValorParametrosController < ApplicationController
  before_action :set_valor_parametro, only: [:show, :edit, :update, :destroy]
  require 'pp'
  # GET /valor_parametros
  # GET /valor_parametros.json
  def index   
      @sw=params[:sw]
       @valor_parametros=ValorParametro.where("parametro_id = ?",params[:id])
     
      # @valor_parametros = ValorParametro.all
   
    render layout: "application1"
  end

  # GET /valor_parametros/1
  # GET /valor_parametros/1.json
  def show
     render layout: "application1"
  end

  # GET /valor_parametros/new
  def new
    @valor_parametro = ValorParametro.new
    render layout: "application1"
  end

  # GET /valor_parametros/1/edit
  def edit
     render layout: "application1"
  end

  # POST /valor_parametros
  # POST /valor_parametros.json
  def create
    @valor_parametro = ValorParametro.new(valor_parametro_params)

    respond_to do |format|
      if @valor_parametro.save
        format.html { redirect_to @valor_parametro, notice: 'Valor parametro was successfully created.' }
        format.json { render :show, status: :created, location: @valor_parametro }
      else
        format.html { render :new }
        format.json { render json: @valor_parametro.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /valor_parametros/1
  # PATCH/PUT /valor_parametros/1.json
  def update
    respond_to do |format|
      if @valor_parametro.update(valor_parametro_params)
        format.html { redirect_to @valor_parametro, notice: 'Valor parametro was successfully updated.' }
        format.json { render :show, status: :ok, location: @valor_parametro }
      else
        format.html { render :edit }
        format.json { render json: @valor_parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valor_parametros/1
  # DELETE /valor_parametros/1.json
  def destroy
    @valor_parametro.destroy
    respond_to do |format|
      format.html { redirect_to valor_parametros_url, notice: 'Valor parametro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valor_parametro
      @valor_parametro = ValorParametro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valor_parametro_params
      params.require(:valor_parametro).permit(:parametro_id, :valor, :orden, :estadoValorParametro, :eliminado)
    end
end

app/helpers/valor_parametros_helper.rb
module ValorParametrosHelper
end

app/views/valor_parametros/_form.html.erb
<%= form_with(model: valor_parametro, local: true) do |form| %>
  <% if valor_parametro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valor_parametro.errors.count, "error") %> prohibited this valor_parametro from being saved:</h2>

      <ul>
      <% valor_parametro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row col-sm-4">
    <%= form.label :parametro %>
    <%= form.number_field :parametro_id, id: :valor_parametro_parametro_id, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :valor %>
    <%= form.text_field :valor, id: :valor_parametro_valor, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :orden %>
    <%= form.text_field :orden, id: :valor_parametro_orden, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label "Estado" %>
    <%= form.text_field :estadoValorParametro, id: :valor_parametro_estadoValorParametro, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4" hidden>
    <%= form.label :eliminado %>
    <%= form.hidden_field :eliminado, id: :valor_parametro_eliminado , class:"form-control", :value => 0%>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", :class=>"btn btn-success" %>
  </div>
<% end %>

app/views/valor_parametros/edit.html.erb
<h1>Editing Valor Parametro</h1>

<%= render 'form', valor_parametro: @valor_parametro %>

<%= link_to 'Eliminar', @valor_parametro, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %>
|
<%= link_to 'Regresar', valor_parametros_path, class: "btn btn-secondary" %>

app/views/valor_parametros/index.html.erb
<h4>Valor Parametros</h4>
<hr class="division">

   <%= link_to 'Nuevo', new_valor_parametro_path,class:'btn btn-primary btn-sm' %>

<p id="notice"><%= notice %></p>
<table id="valor_parametro_data" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th>Parametro</th>
      <th>Valor</th>
      <th>Orden</th>
      <th>Estado</th>     
     
    </tr>
  </thead>
  <tbody>
    <% @valor_parametros.each do |valor_parametro| %>
      <tr>
        <td><%= valor_parametro.id %></td>
        <td><%= valor_parametro.parametro_id %></td>
        <td><%= valor_parametro.valor %></td>
        <td><%= valor_parametro.orden %></td>
        <td><%= valor_parametro.estadoValorParametro %></td>               
        </tr>
    <% end %>
  </tbody>
</table>

 <script>
    jQuery.noConflict();
    jQuery(document).ready(function(){     
      jQuery('#valor_parametro_data').DataTable();       
    });
  
</script>

app/views/valor_parametros/new.html.erb
<h4>Nuevo Valor Parametro</h4>
<hr>
<%= link_to 'Regresar', valor_parametros_path,class:"btn btn-secondary"  %>
<%= render 'form', valor_parametro: @valor_parametro %>

app/views/valor_parametros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parametroid:</strong>
  <%= @valor_parametro.parametroId %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @valor_parametro.valor %>
</p>

<p>
  <strong>Orden:</strong>
  <%= @valor_parametro.orden %>
</p>

<p>
  <strong>Estadovalorparametro:</strong>
  <%= @valor_parametro.estadoValorParametro %>
</p>

<p>
  <strong>Eliminado:</strong>
  <%= @valor_parametro.eliminado %>
</p>

<%= link_to 'Modificar', edit_valor_parametro_path(@valor_parametro), class: "btn btn-success" %> |
<%= link_to 'Regresar', valor_parametros_path, class: "btn btn-secondary" %>