config/routes.rb
Rails.application.routes.draw do

  resources :personas
  resources :anexos
  resources :proveedores
  resources :equipos
  resources :consumos
  resources :facturas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login' # Por default ejecuta el controlador seguridad y el metodo login
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/inicio', to:'inicio#casa'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  get '/consumo_lista/:id', to: "consumos#index"
  get '/anexos_lista', to: "anexos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rol_opcion_operacione.rb
# == Schema Information
#
# Table name: rol_opcion_operaciones
#
#  id          :integer          not null, primary key
#  idrol       :integer
#  idoperacion :integer
#  eliminado   :integer          default(0)
#  estadorolop :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  opcione_id  :integer
#  usuario_id  :integer
#

class RolOpcionOperacione < ApplicationRecord
	belongs_to :opcione
	belongs_to :usuario
end

app/controllers/rol_opcion_operaciones_controller.rb
class RolOpcionOperacionesController < ApplicationController
  before_action :set_rol_opcion_operacione, only: [:show, :edit, :update, :destroy]

  include Servicios
  # GET /rol_opcion_operaciones
  # GET /rol_opcion_operaciones.json
  def index
    @rol_opcion_operaciones = RolOpcionOperacione.all
  end

  # GET /rol_opcion_operaciones/1
  # GET /rol_opcion_operaciones/1.json
  def show
     @roles = TraerParametros(2)
     @operaciones=TraerParametros(3)
  end

  # GET /rol_opcion_operaciones/new
  def new
    @rol_opcion_operacione = RolOpcionOperacione.new
    @roles = TraerParametros(2)
    @operaciones=TraerParametros(3)
  end

  # GET /rol_opcion_operaciones/1/edit
  def edit
     @roles = TraerParametros(2)
     @operaciones=TraerParametros(3)
  end

  # POST /rol_opcion_operaciones
  # POST /rol_opcion_operaciones.json
  def create
    @rol_opcion_operacione = RolOpcionOperacione.new(rol_opcion_operacione_params)

    respond_to do |format|
      if @rol_opcion_operacione.save
        format.html { redirect_to @rol_opcion_operacione, notice: 'Rol opcion operacione was successfully created.' }
        format.json { render :show, status: :created, location: @rol_opcion_operacione }
      else
        format.html { render :new }
        format.json { render json: @rol_opcion_operacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rol_opcion_operaciones/1
  # PATCH/PUT /rol_opcion_operaciones/1.json
  def update
    respond_to do |format|
      if @rol_opcion_operacione.update(rol_opcion_operacione_params)
        format.html { redirect_to @rol_opcion_operacione, notice: 'Rol opcion operacione was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol_opcion_operacione }
      else
        format.html { render :edit }
        format.json { render json: @rol_opcion_operacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rol_opcion_operaciones/1
  # DELETE /rol_opcion_operaciones/1.json
  def destroy
    @rol_opcion_operacione.destroy
    respond_to do |format|
      format.html { redirect_to rol_opcion_operaciones_url, notice: 'Rol opcion operacione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol_opcion_operacione
      @rol_opcion_operacione = RolOpcionOperacione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_opcion_operacione_params
      params.require(:rol_opcion_operacione).permit(:usuario_id, :opcione_id, :idrol, :idoperacion, :eliminado, :estadorolop)
    end
end

app/helpers/rol_opcion_operaciones_helper.rb
module RolOpcionOperacionesHelper
end

app/views/rol_opcion_operaciones/_form.html.erb
<%= form_with(model: rol_opcion_operacione, local: true) do |form| %>
  <% if rol_opcion_operacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol_opcion_operacione.errors.count, "error") %> prohibited this rol_opcion_operacione from being saved:</h2>

      <ul>
      <% rol_opcion_operacione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group row col-sm-4">
    <%= form.label "Usuario" %>
    <%= form.number_field :usuario_id, id: :rol_opcion_operacione_usuario_id, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label "rol" %>
    <%= form.number_field :idrol, id: :rol_opcion_operacione_idrol, class:"form-control"%>
  </div>
<div class="form-group row col-sm-4">
    <%= form.label "Opcion" %>
    <%= form.number_field :opcione_id, id: :rol_opcion_operacione_opcione_id, class:"form-control"%>
  </div>
  <div class="form-group row col-sm-4">
    <%= form.label "Operación" %>
    <%= form.number_field :idoperacion, id: :rol_opcion_operacione_idoperacion, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :eliminado %>
    <%= form.number_field :eliminado, id: :rol_opcion_operacione_eliminado, class:"form-control"%>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label "Estado" %>
    <%= form.text_field :estadorolop, id: :rol_opcion_operacione_estadorolop, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit  "Guardar", :class=>"btn btn-secondary" %>
    <%= link_to 'Eliminar', rol_opcion_operacione, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %>
  </div>
<% end %>

app/views/rol_opcion_operaciones/edit.html.erb
<h4>Modificar Seguridad</h4>
<hr class="division">
<%= render 'form', rol_opcion_operacione: @rol_opcion_operacione %>

<%= link_to 'Mostrar', @rol_opcion_operacione %> |
<%= link_to 'Regresar', rol_opcion_operaciones_path %>

app/views/rol_opcion_operaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rol Opcion Operaciones</h1>

<table>
  <thead>
    <tr>
      <th>Idrol</th>
      <th>Idoperacion</th>
      <th>Eliminado</th>
      <th>Estadorolop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rol_opcion_operaciones.each do |rol_opcion_operacione| %>
      <tr>
        <td><%= rol_opcion_operacione.idrol %></td>
        <td><%= rol_opcion_operacione.idoperacion %></td>
        <td><%= rol_opcion_operacione.eliminado %></td>
        <td><%= rol_opcion_operacione.estadorolop %></td>
        <td><%= link_to 'Show', rol_opcion_operacione %></td>
        <td><%= link_to 'Edit', edit_rol_opcion_operacione_path(rol_opcion_operacione) %></td>
        <td><%= link_to 'Destroy', rol_opcion_operacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rol Opcion Operacione', new_rol_opcion_operacione_path %>

app/views/rol_opcion_operaciones/new.html.erb
<h4>Nuevo Rol Opción Operacion</h4>
<%= link_to 'Regresar', rol_opcion_operaciones_path %>
<hr class="division">
<%= render 'form', rol_opcion_operacione: @rol_opcion_operacione %>

app/views/rol_opcion_operaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idrol:</strong>
  <%= @rol_opcion_operacione.idrol %>
</p>

<p>
  <strong>Idoperacion:</strong>
  <%= @rol_opcion_operacione.idoperacion %>
</p>

<p>
  <strong>Eliminado:</strong>
  <%= @rol_opcion_operacione.eliminado %>
</p>

<p>
  <strong>Estadorolop:</strong>
  <%= @rol_opcion_operacione.estadorolop %>
</p>

<%= link_to 'Edit', edit_rol_opcion_operacione_path(@rol_opcion_operacione) %> |
<%= link_to 'Back', rol_opcion_operaciones_path %>